game_world = {
    "Genoa": {"Marseille": 4, "Roma": 5, "Palma": 8, "Cagliari": 7, "Barcelona": 7},
    "Cagliari": {"Genoa": 7, "Tunis": 2, "Roma": 4},
    "Roma": {"Genoa": 5, "Siracusa": 6, "Cagliari": 4},
    "Marseille": {"Genoa": 4, "Palma": 5, "Barcelona": 4, "Cagliari": 5},
    "Barcelona": {"Marseille": 4, "Valencia": 3, "Palma": 3, "Genoa": 7},
    "Valencia": {"Algiers": 4, "Palma": 2, "Barcelona": 3, "Sevilla": 12},
    "Palma": {"Valencia": 3, "Algiers": 3, "Marseille": 5, "Barcelona": 3},
    "Sevilla": {"Valencia": 12, "Algiers": 12},
    "Algiers": {"Valencia": 4, "Palma": 3,"Tunis": 5,"Sevilla": 12},
    "Tunis": {"Algiers": 5, "Siracusa": 3, "Malta": 2, "Cagliari": 2, "Tripoli": 3},
    "Siracusa": {"Tunis": 2, "Roma": 6, "Malta": 1, "Taranto": 3, "Corfu": 4},
    "Malta": {"Siracusa": 1, "Tunis": 2, "Tripoli": 2},
    "Tripoli": {"Malta": 2, "Tunis": 3, "Benghazi": 3},
    "Benghazi": {"Tripoli": 3, "Alexandria": 6},
    "Taranto": {"Siracusa": 3, "Corfu": 2, "Durres": 3},
    "Durres": {"Taranto": 3, "Corfu": 2, "Zadar": 5, "Ancona": 5},
    "Zadar": {"Venice": 3, "Ancona": 2, "Durres": 5},
    "Ancona": {"Venice": 3, "Zadar": 2, "Durres": 5},
    "Venice": {"Ancona": 3, "Zadar": 3},
    "Corfu": {"Durres": 2, "Taranto": 2, "Kalamata": 3, "Siracusa": 4},
    "Kalamata": {"Corfu": 3, "Athens": 3, "Heraklion": 3},
    "Athens": {"Kalamata": 3, "Smyrna": 4, "Thessaloniki": 5, "Heraklion": 5},
    "Thessaloniki": {"Athens": 5, "Smyrna": 6, "Constantinople": 10},
    "Constantinople": {"Thessaloniki": 10, "Smyrna": 8},
    "Smyrna": {"Constantinople": 8, "Thessaloniki": 6, "Athens": 4, "Rhodes": 4},
    "Heraklion": {"Kalamata": 5, "Athens": 5, "Rhodes": 5, "Alexandria": 12},
    "Rhodes": {"Smyrna": 4, "Heraklion": 5, "Side": 6, "Famagusta": 8, "Alexandria": 14},
    "Side": {"Rhodes": 6, "Famagusta": 5, "Hadrianopolis": 6},
    "Famagusta": {"Alexandria": 10, "Side": 5, "Rhodes": 8, "Hadrianopolis": 5, "Tortosa": 6},
    "Hadrianopolis": {"Side": 6, "Famagusta": 5, "Tortosa": 6},
    "Tortosa": {"Hadrianopolis": 6, "Famagusta": 6, "Acre": 3, "Alexandria": 10},
    "Acre": {"Tortosa": 3, "Alexandria": 8},
    "Alexandria": {"Acre": 8, "Tortosa": 10, "Famagusta": 10, "Rhodes": 14, "Heraklion": 12, "Benghazi": 6},
}

ports = {
    "Genoa":            {"map_x": 165, "map_y": 194},
    "Cagliari":         {"map_x": 162, "map_y": 246},
    "Roma":             {"map_x": 178, "map_y": 210},
    "Marseille":        {"map_x": 139, "map_y": 199},
    "Barcelona":        {"map_x": 116, "map_y": 222},
    "Valencia":         {"map_x": 103, "map_y": 240},
    "Palma":            {"map_x": 121, "map_y": 239},
    "Sevilla":          {"map_x": 59, "map_y": 260},
    "Algiers":          {"map_x": 133, "map_y": 270},
    "Tunis":            {"map_x": 173, "map_y": 267},
    "Siracusa":         {"map_x": 207, "map_y": 262},
    "Malta":            {"map_x": 203, "map_y": 281},
    "Tripoli":          {"map_x": 185, "map_y": 310},
    "Benghazi":         {"map_x": 238, "map_y": 318},
    "Taranto":          {"map_x": 223, "map_y": 238},
    "Durres":           {"map_x": 240, "map_y": 224},
    "Zadar":            {"map_x": 217, "map_y": 201},
    "Ancona":           {"map_x": 192, "map_y": 197},
    "Venice":           {"map_x": 196, "map_y": 187},
    "Corfu":            {"map_x": 240, "map_y": 244},
    "Kalamata":         {"map_x": 254, "map_y": 263},
    "Athens":           {"map_x": 264, "map_y": 255},
    "Thessaloniki":     {"map_x": 260, "map_y": 233},
    "Constantinople":   {"map_x": 294, "map_y": 233},
    "Smyrna":           {"map_x": 292, "map_y": 250},
    "Heraklion":        {"map_x": 269, "map_y": 278},
    "Rhodes":           {"map_x": 291, "map_y": 261},
    "Side":             {"map_x": 308, "map_y": 252},
    "Famagusta":        {"map_x": 327, "map_y": 278},
    "Hadrianopolis":    {"map_x": 346, "map_y": 252},
    "Tortosa":          {"map_x": 346, "map_y": 281},
    "Acre":             {"map_x": 342, "map_y": 314},
    "Alexandria":       {"map_x": 298, "map_y": 329},
}
